---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    # - { name: homebrew, when: ansible_os_family == "Darwin" }
    # - { name: geerlingguy.dotfiles, tags: [dotfiles] }
  tasks:
    - include: tasks/main.yml
