---

- name: Configure the Dock
  block:
    - name: Disable showing recent files
      shell: "defaults write com.apple.dock show-recents -bool false"

    - name: Remove specified items from Dock
      shell: "dockutil --remove '{{ item }}'"
      ignore_errors: true
      with_items: "{{ dockitems_to_remove }}"


    - name: Check if items in dock exist
      shell: "dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'"
      with_items: "{{ dockitems_to_persist }}"


    - name: Fix order
      shell: "dockutil --move '{{ item.name }}' --position {{ item.pos }}"
      with_items: "{{ dockitems_to_persist }}"
  tags:
    - macos
    - dock


- name: Ensure standby mode behaves properly
  shell: pmset -a {{ item }}
  become: true
  with_items:
    - destroyfvkeyonstandby 1
    - powernap 0
    - standby 0
    - standbydelayhigh 0
    - standbydelaylow 0
    - autopoweroff 0


- name: Configure incoming Firewall
  shell: /usr/libexec/ApplicationFirewall/socketfilterfw --{{ item.name }} {{ item.state }}
  become: true
  with_items:
    - name: setglobalstate
      state: on
    - name: setloggingmode
      state: on
    - name: setstealthmode
      state: on
    - name: setallowsigned
      state: off
    - name: setallowsignedapp
      state: off
  register: socketfilterfw_configuration


- name: Reload socketfilterfw
  shell: pkill -HUP socketfilterfw
  become: true
  when: socketfilterfw_configuration.changed


- name: Disable auto-captive portal detection
  shell: defaults write /Library/Preferences/SystemConfiguration/com.apple.captive.control.plist Active -bool false
  become: true


- name: Check if .curlrc exists
  stat:
    path: ~/.curlrc
  register: curlrc_check


- name: Secure CURL
  copy:
    src: files/curlrc
    dest: ~/.curlrc
  when: curlrc_check.stat.exists == False
